"Filed out from Dolphin Smalltalk 7"!

SmalltalkSearchPresenter subclass: #JadeiteSmalltalkSearchPresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteSmalltalkSearchPresenter guid: (GUID fromString: '{acc8d649-4597-483b-aec3-b5df92c1508c}')!
JadeiteSmalltalkSearchPresenter comment: ''!
!JadeiteSmalltalkSearchPresenter categoriesForClass!Development! !
!JadeiteSmalltalkSearchPresenter methodsFor!

applyOptions
	"Private - Apply the class options to the receiver"
	view maxCompletionListHeight: 10.
	view maxCompletionListWidth: 40.
	view autoCompletionSeparator: $\x7F! !
!JadeiteSmalltalkSearchPresenter categoriesFor: #applyOptions!private! !

