"Filed out from Dolphin Smalltalk 7"!

TreeView subclass: #JadeiteTreeView
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteTreeView guid: (GUID fromString: '{3dd705c5-e522-4b7a-ae54-bbcfc4a3ab71}')!
JadeiteTreeView comment: ''!
!JadeiteTreeView categoriesForClass!MVP-Views! !
!JadeiteTreeView class methodsFor!

defaultModel
	"Answer a default model to be assigned to the receiver when it is initialized."

	^JadeiteTreeModel new! !
!JadeiteTreeView class categoriesFor: #defaultModel!models!public! !

