"Filed out from Dolphin Smalltalk 7"!

JadeiteMethodListBrowser subclass: #JadeiteFindStringMethodListBrowser
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteFindStringMethodListBrowser guid: (GUID fromString: '{d454656d-41bf-4d2c-9ef4-92244eff7660}')!
JadeiteFindStringMethodListBrowser comment: ''!
!JadeiteFindStringMethodListBrowser categoriesForClass!Unclassified! !
!JadeiteFindStringMethodListBrowser methodsFor!

presenterClass

	^JadeiteFindStringMethodListPresenter! !
!JadeiteFindStringMethodListBrowser categoriesFor: #presenterClass!private! !

