"Filed out from Dolphin Smalltalk 7"!

TreePresenter subclass: #JadeiteTreePresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteTreePresenter guid: (GUID fromString: '{038b211e-91ab-44d9-a164-de38fd29207c}')!
JadeiteTreePresenter comment: ''!
!JadeiteTreePresenter categoriesForClass!MVP-Presenters! !
!JadeiteTreePresenter class methodsFor!

defaultModel
	"Answer a default model to be assigned to the receiver when it
	is initialized."

	^JadeiteTreeModel new! !
!JadeiteTreePresenter class categoriesFor: #defaultModel!models!public! !

