"Filed out from Dolphin Smalltalk 7"!

CodeSourcePresenter subclass: #JadeiteGitCommandPresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteGitCommandPresenter guid: (GUID fromString: '{3b753870-03a0-4f45-841a-58e3b287e903}')!
JadeiteGitCommandPresenter comment: ''!
!JadeiteGitCommandPresenter categoriesForClass!Unclassified! !
