"Filed out from Dolphin Smallalk"!

STON subclass: #JadeiteSTON
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteSTON guid: (GUID fromString: '{f50f4364-7a1c-44bb-bc6e-b5a3b829791a}')!
JadeiteSTON comment: ''!
!JadeiteSTON categoriesForClass!STON-Core-Base! !
!JadeiteSTON class methodsFor!

writer
	^JadeiteSTONWriter basicNew initialize! !
!JadeiteSTON class categoriesForMethods!
writer!accessing!public! !
!

