"Filed out from Dolphin Smalltalk 7"!

JadeiteInspectorTestCase subclass: #JadeiteDataCuratorInspectorTestCase
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteDataCuratorInspectorTestCase guid: (GUID fromString: '{e9bef516-9ceb-4fa5-9f71-0673eae11259}')!
JadeiteDataCuratorInspectorTestCase comment: ''!
!JadeiteDataCuratorInspectorTestCase categoriesForClass!Unclassified! !
!JadeiteDataCuratorInspectorTestCase methodsFor!

setUp
	user := 'DataCurator'.
	super setUp!

tearDown
	super tearDown.
	user := nil! !
!JadeiteDataCuratorInspectorTestCase categoriesFor: #setUp!public!setup teardown! !
!JadeiteDataCuratorInspectorTestCase categoriesFor: #tearDown!public!setup teardown! !

