"Filed out from Dolphin Smalltalk 7"!

JadeiteMethodSourcePresenter subclass: #JadeiteBreakpointBrowserSourcePresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteBreakpointBrowserSourcePresenter guid: (GUID fromString: '{bbd0d012-cc15-44a2-b129-7344ceb3e3e1}')!
JadeiteBreakpointBrowserSourcePresenter comment: ''!
!JadeiteBreakpointBrowserSourcePresenter categoriesForClass!Unclassified! !
!JadeiteBreakpointBrowserSourcePresenter methodsFor!

setDefaultMethod
	documentPresenter
		value: String new;
		isModified: false;
		isReadOnly: false;
		yourself! !
!JadeiteBreakpointBrowserSourcePresenter categoriesFor: #setDefaultMethod!public! !

