"Filed out from Dolphin Smalltalk 7"!

JadeiteInspectorTestCase subclass: #JadeiteInspectorDataCuratorTestCase
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteInspectorDataCuratorTestCase guid: (GUID fromString: '{e9bef516-9ceb-4fa5-9f71-0673eae11259}')!
JadeiteInspectorDataCuratorTestCase comment: ''!
!JadeiteInspectorDataCuratorTestCase categoriesForClass!Unclassified! !
!JadeiteInspectorDataCuratorTestCase methodsFor!

setUp
	user := 'DataCurator'.
	super setUp!

tearDown
	super tearDown.
	user := nil! !
!JadeiteInspectorDataCuratorTestCase categoriesFor: #setUp!public!setup teardown! !
!JadeiteInspectorDataCuratorTestCase categoriesFor: #tearDown!public!setup teardown! !

