"Filed out from Dolphin Smallalk"!

DolphinSTONWriter subclass: #JadeiteSTONWriter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeiteSTONWriter guid: (GUID fromString: '{307288e0-81e6-4247-aecd-94d08405fec7}')!
JadeiteSTONWriter comment: ''!
!JadeiteSTONWriter categoriesForClass!STON-Core-Writer! !
!JadeiteSTONWriter methodsFor!

initialize
	super initialize. 
	asciiOnly := true. ! !
!JadeiteSTONWriter categoriesForMethods!
initialize!public! !
!

