"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_7 subclass: #LibGciRpc64_3_7_0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_7_0 guid: (GUID fromString: '{dc7cf2a5-e03f-498c-9267-11ac3c23b34d}')!
LibGciRpc64_3_7_0 comment: ''!
!LibGciRpc64_3_7_0 categoriesForClass!Unclassified! !
!LibGciRpc64_3_7_0 class methodsFor!

displayName   ^'64-bit 3.7.0'!

fileNameSearch   ^'libgcirpc-3.7.0-32.dll'! !
!LibGciRpc64_3_7_0 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_7_0 class categoriesFor: #fileNameSearch!public! !

