"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_5 subclass: #LibGciRpc64_3_5_1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_5_1 guid: (GUID fromString: '{78953818-2e6a-45dc-9a9c-86bbd928c136}')!
LibGciRpc64_3_5_1 comment: ''!
!LibGciRpc64_3_5_1 categoriesForClass!Unclassified! !
!LibGciRpc64_3_5_1 class methodsFor!

displayName

	^'64-bit 3.5.1'.
!

fileNameSearch

	^'libgcirpc-3.5.1-32.dll'.
! !
!LibGciRpc64_3_5_1 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_5_1 class categoriesFor: #fileNameSearch!public! !

