"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_2 guid: (GUID fromString: '{8e47f9d9-65ec-47c0-b387-6aa218b49fc4}')!
LibGciRpc64_3_6_2 comment: ''!
!LibGciRpc64_3_6_2 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_2 class methodsFor!

displayName
	^'64-bit 3.6.2 unreleased'!

fileNameSearch
	^'libgcirpc-3.6.2-32.dll'! !
!LibGciRpc64_3_6_2 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_2 class categoriesFor: #fileNameSearch!public! !

