"Filed out from Dolphin Smallalk"!

LibGciRpc64_3_7 subclass: #LibGciRpc64_3_7_0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_7_0 guid: (GUID fromString: '{e171cbf5-c460-4c71-a453-fb73bd2a8e5b}')!
LibGciRpc64_3_7_0 comment: ''!
!LibGciRpc64_3_7_0 categoriesForClass!Unclassified! !
!LibGciRpc64_3_7_0 class methodsFor!

displayName   ^'64-bit 3.7.0'!

fileNameSearch   ^'libgcirpc-3.7.0-32.dll'!

supportsRowanV30

	^true! !
!LibGciRpc64_3_7_0 class categoriesForMethods!
displayName!public! !
fileNameSearch!public! !
supportsRowanV30!public!testing! !
!

