"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_1 guid: (GUID fromString: '{d1da0ea0-d027-49af-a6dd-e26f8c397b43}')!
LibGciRpc64_3_6_1 comment: ''!
!LibGciRpc64_3_6_1 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_1 class methodsFor!

displayName

	^'64-bit 3.6.1'.
!

fileNameSearch

	^'libgcirpc-3.6.1-32.dll'.
! !
!LibGciRpc64_3_6_1 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_1 class categoriesFor: #fileNameSearch!public! !

