"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_3
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_3 guid: (GUID fromString: '{f968e552-abbc-4ec7-bf9c-2ebcd2c58e64}')!
LibGciRpc64_3_6_3 comment: ''!
!LibGciRpc64_3_6_3 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_3 class methodsFor!

displayName

	^'64-bit 3.6.3'.
!

fileNameSearch

	^'libgcirpc-3.6.3-32.dll'.
! !
!LibGciRpc64_3_6_3 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_3 class categoriesFor: #fileNameSearch!public! !

