"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_4
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_4 guid: (GUID fromString: '{c3f317ae-47f7-4a48-8514-088cb1426906}')!
LibGciRpc64_3_6_4 comment: ''!
!LibGciRpc64_3_6_4 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_4 class methodsFor!

displayName

	^'64-bit 3.6.4'.
!

fileNameSearch

	^'libgcirpc-3.6.4-32.dll'.
! !
!LibGciRpc64_3_6_4 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_4 class categoriesFor: #fileNameSearch!public! !

