"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_2 guid: (GUID fromString: '{47a921b6-2838-4d61-ad80-0514c8e74f47}')!
LibGciRpc64_3_6_2 comment: ''!
!LibGciRpc64_3_6_2 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_2 class methodsFor!

displayName

	^'64-bit 3.6.2'.
!

fileNameSearch

	^'libgcirpc-3.6.2-32.dll'.
! !
!LibGciRpc64_3_6_2 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_2 class categoriesFor: #fileNameSearch!public! !

