"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_6 subclass: #LibGciRpc64_3_6_0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_6_0 guid: (GUID fromString: '{4d98692e-9da3-4009-b329-3c977bcf940d}')!
LibGciRpc64_3_6_0 comment: ''!
!LibGciRpc64_3_6_0 categoriesForClass!Unclassified! !
!LibGciRpc64_3_6_0 class methodsFor!

displayName   ^'64-bit 3.6.0'!

fileNameSearch   ^'libgcirpc-3.6.0-32.dll'! !
!LibGciRpc64_3_6_0 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_6_0 class categoriesFor: #fileNameSearch!public! !

