"Filed out from Dolphin Smallalk"!

RowanInspectorService subclass: #RowanSpecificationService
	instanceVariableNames: 'loadSpecOop loadSpecPath session comment conditionalAttributes platformProperties'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanSpecificationService guid: (GUID fromString: '{b77424a1-b7be-44f2-b1e1-53fe4eff289d}')!
RowanSpecificationService comment: ''!
!RowanSpecificationService categoriesForClass!Unclassified! !
