"Filed out from Dolphin Smalltalk 7"!

RowanDefinitionService subclass: #RowanClassDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanClassDefinitionService guid: (GUID fromString: '{f93a608f-ab0b-4803-8a49-c3aa9fb86efb}')!
RowanClassDefinitionService comment: ''!
!RowanClassDefinitionService categoriesForClass!Unclassified! !
