"Filed out from Dolphin Smalltalk 7"!

RowanService subclass: #RowanDefinitionService
	instanceVariableNames: 'name properties'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanDefinitionService guid: (GUID fromString: '{0b5e75f1-b946-476e-a2e0-7d358db0c680}')!
RowanDefinitionService comment: ''!
!RowanDefinitionService categoriesForClass!Unclassified! !
!RowanDefinitionService methodsFor!

name
	^name!

name: anObject
	name := anObject!

properties
	^properties!

properties: anObject
	properties := anObject! !
!RowanDefinitionService categoriesFor: #name!accessing!private! !
!RowanDefinitionService categoriesFor: #name:!accessing!private! !
!RowanDefinitionService categoriesFor: #properties!accessing!private! !
!RowanDefinitionService categoriesFor: #properties:!accessing!private! !

