"Filed out from Dolphin Smalltalk 7"!

RowanDefinitionService subclass: #RowanPackageDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackageDefinitionService guid: (GUID fromString: '{3a8b10d9-6955-41ae-bde0-4aa4b749b21b}')!
RowanPackageDefinitionService comment: ''!
!RowanPackageDefinitionService categoriesForClass!Unclassified! !
