"Filed out from Dolphin Smallalk"!

RowanPackageGroupService subclass: #RowanPackageGroupDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackageGroupDefinitionService guid: (GUID fromString: '{a6516859-406d-4098-9e94-1f3be846640d}')!
RowanPackageGroupDefinitionService comment: ''!
!RowanPackageGroupDefinitionService categoriesForClass!Unclassified! !
