"Filed out from Dolphin Smallalk"!

RowanCommandResult subclass: #RowanGlobalsUpdate
	instanceVariableNames: 'globals'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanGlobalsUpdate guid: (GUID fromString: '{5814b892-8cb7-4648-a140-d028cf234155}')!
RowanGlobalsUpdate comment: ''!
!RowanGlobalsUpdate categoriesForClass!Unclassified! !
!RowanGlobalsUpdate methodsFor!

globalsUpdate: aPresenter
	aPresenter list: globals.! !
!RowanGlobalsUpdate categoriesForMethods!
globalsUpdate:!public! !
!

