"Filed out from Dolphin Smalltalk 7"!

RowanService subclass: #RowanAutoCommitService
	instanceVariableNames: 'autoCommit'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanAutoCommitService guid: (GUID fromString: '{32b30a33-c470-43de-befd-cab5cd6cd8a7}')!
RowanAutoCommitService comment: ''!
!RowanAutoCommitService categoriesForClass!Unclassified! !
!RowanAutoCommitService methodsFor!

autoCommitUpdate: browser
	browser autoCommit: autoCommit! !
!RowanAutoCommitService categoriesFor: #autoCommitUpdate:!public!updating! !

