"Filed out from Dolphin Smallalk"!

RowanService subclass: #RowanLoadSpecService
	instanceVariableNames: 'loadSpecOop loadSpecPath'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanLoadSpecService guid: (GUID fromString: '{e7cc648a-a434-4120-a63b-3cd20cebf9d4}')!
RowanLoadSpecService comment: ''!
!RowanLoadSpecService categoriesForClass!Unclassified! !
!RowanLoadSpecService methodsFor!

loadSpecPath
	^loadSpecPath!

loadSpecPath: anObject
	loadSpecPath := anObject! !
!RowanLoadSpecService categoriesForMethods!
loadSpecPath!accessing!private! !
loadSpecPath:!accessing!private! !
!

