"Filed out from Dolphin Smalltalk 7"!

RowanDefinitionService subclass: #RowanComponentDefinitionService
	instanceVariableNames: 'subcomponentDefinitions'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanComponentDefinitionService guid: (GUID fromString: '{5843d4f0-ef18-48bc-bb42-37ec2b129736}')!
RowanComponentDefinitionService comment: ''!
!RowanComponentDefinitionService categoriesForClass!Unclassified! !
