"Filed out from Dolphin Smallalk"!

RowanComponentDefinitionService subclass: #RowanSubcomponentDefinitionService
	instanceVariableNames: 'condition'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanSubcomponentDefinitionService guid: (GUID fromString: '{9a6679d7-d083-4d27-b576-4a5b14369cc9}')!
RowanSubcomponentDefinitionService comment: ''!
!RowanSubcomponentDefinitionService categoriesForClass!Unclassified! !
!RowanSubcomponentDefinitionService methodsFor!

condition
	^condition!

condition: anObject
	condition := anObject!

isSubcomponent

	^true! !
!RowanSubcomponentDefinitionService categoriesForMethods!
condition!accessing!private! !
condition:!accessing!private! !
isSubcomponent!public!testing! !
!

