"Filed out from Dolphin Smallalk"!

RowanPresenter subclass: #RowanPackagePresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackagePresenter guid: (GUID fromString: '{abf1f655-8d1f-45af-a0fd-bcb6e982373e}')!
RowanPackagePresenter comment: ''!
!RowanPackagePresenter categoriesForClass!Unclassified! !
!RowanPackagePresenter methodsFor!

createNewPackage! !
!RowanPackagePresenter categoriesForMethods!
createNewPackage!public! !
!

