"Filed out from Dolphin Smallalk"!

RowanComponentDefinitionService subclass: #RowanPackageGroupService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackageGroupService guid: (GUID fromString: '{b1767a68-7a64-41dd-b0d1-187de3d85dde}')!
RowanPackageGroupService comment: ''!
!RowanPackageGroupService categoriesForClass!Unclassified! !
