"Filed out from Dolphin Smallalk"!

RowanSubcomponentDefinitionService subclass: #RowanPlatformSubcomponentDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPlatformSubcomponentDefinitionService guid: (GUID fromString: '{fa07ef47-b4d3-4b32-82d1-0ac42f8b318a}')!
RowanPlatformSubcomponentDefinitionService comment: ''!
!RowanPlatformSubcomponentDefinitionService categoriesForClass!Unclassified! !
!RowanPlatformSubcomponentDefinitionService methodsFor!

isPlatformSubcomponent

	^true! !
!RowanPlatformSubcomponentDefinitionService categoriesForMethods!
isPlatformSubcomponent!public!testing! !
!

