"Filed out from Dolphin Smallalk"!

Object subclass: #TestCase2
	instanceVariableNames: 'testSelector'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TestCase2 guid: (GUID fromString: '{9ff75f6c-7676-479a-bf74-c8f6378e1bba}')!
TestCase2 comment: 'These tests aren''t working. Get them out of the SUnit browser until they''re 
fixed - if they are ever fixed.'!
!TestCase2 categoriesForClass!Unclassified! !
