"Filed out from Dolphin Smalltalk 7"!

Object subclass: #TestCase2
	instanceVariableNames: 'testSelector'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TestCase2 guid: (GUID fromString: '{9ff75f6c-7676-479a-bf74-c8f6378e1bba}')!
TestCase2 comment: 'These tests aren''t working. Get them out of the SUnit browser until they''re 
fixed - if ever as they were old Jade tests that were long broken. '!
!TestCase2 categoriesForClass!Unclassified! !
